sudo: required
language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
install:
  - yes "" | sudo -HE ./install.sh
  - pip install -r requirements.txt
  - pip install pylint
  - python multiscanner.py init
script:
  - pytest
  - pylint .
